/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbchanges.gui;

import dbchanges.dal.HistoricosDAO;
import dbchanges.dal.ProjetosDAO;
import dbchanges.dtl.HistoricosDTO;
import dbchanges.dtl.ProjetosDTO;
import java.awt.Component;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Facensa
 */
public class ConsultaHistoricosGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ConsultaHistoricosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbProjetos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbHistoricos = new javax.swing.JTable();
        btnVoltarProjeto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfIdHistoricoFeedback = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTempoRealFeedback = new javax.swing.JTextField();
        btnFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                populateComboboxProject(evt);
            }
        });

        jcbProjetos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbProjetoHistoricosStateChanged(evt);
            }
        });

        jLabel1.setText("Selecione o projeto:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Consulta Históricos");

        jtbHistoricos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data/Hora", "Linhas", "Colunas", "Fks", "Constraints", "Functions", "Triggers", "Indices", "Views", "Tabelas", "Tempo Estimado", "Tempo Real"
            }
        ));
        jScrollPane1.setViewportView(jtbHistoricos);
        if (jtbHistoricos.getColumnModel().getColumnCount() > 0) {
            jtbHistoricos.getColumnModel().getColumn(0).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtbHistoricos.getColumnModel().getColumn(1).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(1).setPreferredWidth(130);
            jtbHistoricos.getColumnModel().getColumn(2).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(2).setPreferredWidth(50);
            jtbHistoricos.getColumnModel().getColumn(3).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtbHistoricos.getColumnModel().getColumn(4).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(4).setPreferredWidth(30);
            jtbHistoricos.getColumnModel().getColumn(5).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(5).setPreferredWidth(70);
            jtbHistoricos.getColumnModel().getColumn(6).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(6).setPreferredWidth(50);
            jtbHistoricos.getColumnModel().getColumn(7).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(7).setPreferredWidth(50);
            jtbHistoricos.getColumnModel().getColumn(8).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(8).setPreferredWidth(50);
            jtbHistoricos.getColumnModel().getColumn(9).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(9).setPreferredWidth(40);
            jtbHistoricos.getColumnModel().getColumn(10).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(10).setPreferredWidth(50);
            jtbHistoricos.getColumnModel().getColumn(11).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(11).setPreferredWidth(100);
            jtbHistoricos.getColumnModel().getColumn(12).setResizable(false);
            jtbHistoricos.getColumnModel().getColumn(12).setPreferredWidth(70);
        }

        btnVoltarProjeto.setText("Voltar");
        btnVoltarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarProjetoActionPerformed(evt);
            }
        });

        jLabel3.setText("Código do Histórico:");

        jLabel4.setText("Tempo Real:");

        btnFeedback.setText("Feedback");
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIdHistoricoFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTempoRealFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVoltarProjeto)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfIdHistoricoFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFeedback)
                    .addComponent(jLabel4)
                    .addComponent(jtfTempoRealFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarProjetoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarProjetoActionPerformed

    private void populateComboboxProject(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_populateComboboxProject
        try {
            ProjetosDAO projetoDao = new ProjetosDAO();
            List<ProjetosDTO> projetos = projetoDao.recuperarProjetosPorNomeComboBox();
            jcbProjetos.getSelectedItem();
            jcbProjetos.removeAll();

            for (ProjetosDTO projeto : projetos) {
                jcbProjetos.addItem(projeto);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaHistoricosGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_populateComboboxProject

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        HistoricosDTO historico = new HistoricosDTO();
        historico.setId(Integer.parseInt(jtfIdHistoricoFeedback.getText()));
        historico.setTempoReal(Integer.parseInt(jtfTempoRealFeedback.getText()));
        HistoricosDAO dao = new HistoricosDAO();
        dao.adicionaFeedback(historico);
        JOptionPane.showMessageDialog(null, "Historico " + jtfIdHistoricoFeedback.getText() + " atualizado com sucesso! ");
        jtfIdHistoricoFeedback.setText("");
        jtfTempoRealFeedback.setText("");
    }//GEN-LAST:event_btnFeedbackActionPerformed

    private void jtbProjetoHistoricosStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbProjetoHistoricosStateChanged
        try {
            ProjetosDTO projeto = (ProjetosDTO) jcbProjetos.getSelectedItem();
            HistoricosDAO historicoDao = new HistoricosDAO();
            List<HistoricosDTO> historicos = historicoDao.recuperarHistoricosJtable(projeto.getId());
            //historicos.size();
            DefaultTableModel modeloTable = (DefaultTableModel) jtbHistoricos.getModel();
            for (HistoricosDTO historico : historicos) {
                modeloTable.addRow(new Object[]{
                    historico.getId(),
                    historico.getDatahora(),
                    historico.getLinhas(),
                    historico.getColunas(),
                    historico.getFks(),
                    historico.getConstraints2(),
                    historico.getFunction2(),
                    historico.getTrigger2(),
                    historico.getIndex2(),
                    historico.getView2(),
                    historico.getTabela(),
                    historico.getTempoEstimado(),
                    historico.getTempoReal()
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtbProjetoHistoricosStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaHistoricosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaHistoricosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnVoltarProjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbProjetos;
    private javax.swing.JTable jtbHistoricos;
    private javax.swing.JTextField jtfIdHistoricoFeedback;
    private javax.swing.JTextField jtfTempoRealFeedback;
    // End of variables declaration//GEN-END:variables
}
